### PR TITLE
Refactor emails notifications in a single interface

### PR DESCRIPTION
**Pull request by skelz0r**
This PR introduces a single and unified interface for notifications for each target api.

The goals are:

1. enable target api manager to easily override behaviour about external notifications for each step of enrollments. The main cases are, for example, adds informations on a CRM, build funnels, trigger customized email (instead of default one on the application).
2. Simplify and refactor all this logic in an isolate service

TODO:

* [x] Add tests to cover all external notifications in order to keep default behaviour intact after refactoring
* [x] Refactor emails notification within EnrollmentsController#trigger 
* [x] Refactor emails notification within EnrollmentsController#create 
* [x] Refactor emails notification within EnrollmentsController#update_rgpd_contact 
* [x] NOT SURE | Refactor emails notification within EnrollmentsController#update_owner 
* [x] Refactor/simplify BaseNotifier
* [ ] Documentation
* NO MORE RELEVANT: they aren't notification, should be refactor in another PR | Refactor bridges calls within `before_transition: :validated`
* [x] Review
* [ ] 🍹

### CODE REVIEW

**Comment by skelz0r** [comment]
@rdubigny should be OK

I will add some documentation in `app/notifiers` folder to explain how to override `BaseNotifier`, perhaps when I'll create the webhook system (we should talk about it too).

This PR only introduces a refactor like we spoke in our last meeting.

**Comment by skelz0r** [comment]
Moreover I began with tests on bridges calls because I thought I'd refactor this part in this PR too, I think it's not a good idea, but I kept the tests, which are relevant (ensure that bridges are called when we validate enrollments for each target api).

**Review by rdubigny — APPROVED** [review]
Merci pour cette belle contribution et pour les tests sur les bridges.

**Comment by rdubigny** [comment]
The CI broke several commit ago as it started throwing error about sql injections in the enrollment index controller. I'll ignore this error for now.

**Pull request merged**
